FROM node:20-alpine

# pnpm を有効化
RUN corepack enable

WORKDIR /app

# 依存解決のために package.* を先にコピー
COPY package.json pnpm-lock.yaml* ./

# インストール
RUN pnpm install

# 残りをコピー
COPY . .

EXPOSE 3000

# 開発サーバーを起動
CMD ["pnpm", "dev"]